name: VLESS Test

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:         # allow manual run

jobs:
  run-vless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Run VLESS test
        run: |
          ./run.sh "vless://b26f0cef-1dc3-4de4-936f-d1b8abd4bce2@origin.connectedbot.site:443?encryption=none&security=tls&sni=zoom.us&allowInsecure=1&type=ws&path=%2F#bo"
